nginx:
  build: nginx
  ports:
    - "443:443"
  links:
    - php
  ports:
    - "443:443"
    - "80:80"
  volumes:
    - "/var/lib/acme:/var/lib/acme"

php:
  build: php
  expose:
    - 80
  volumes:
    - .:/opt/project
  links:
    - db
  container_name: vkmusik_php
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - "POSTGRES_DB=vkmusic"
    - "POSTGRES_USER=vkmusic"
