version: '2'
services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/opt/project
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=vkmusic"
      - "POSTGRES_USER=vkmusic"
