php:
  build: .
  ports:
    - "80:80"
  volumes:
    - .:/opt/project
  links:
    - db
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - "POSTGRES_DB=vkmusic"
    - "POSTGRES_USER=vkmusic"
